<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="Service1.asmxWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/Service1.asmxWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/Service1.asmxWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://tempuri.org/">
    <import location="http://localhost:56333/Service1.asmx?WSDL" namespace="http://tempuri.org/"/>
    <plnk:partnerLinkType name="Service1SoapLinkType">
        <plnk:role name="Service1SoapRole" portType="ns:Service1Soap"/>
    </plnk:partnerLinkType>
</definitions>
